src/Entity/Terrarium.php
<?php

namespace App\Entity;

use DateTimeInterface;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TerrariumRepository")
 */
class Terrarium
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private ?int $id;

    /**
     * @ORM\Column(type="integer")
     */
    private ?int $user_id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private string $name = '';

    /**
     * @ORM\Column(type="string", length=5)
     */
    private string $temperature_range = '';

    /**
     * @ORM\Column(type="string", length=5)
     */
    private string $humidity_range = '';

    /**
     * @ORM\Column(type="string", length=17)
     */
    private string $lighting_schedule = '';

    /**
     * @ORM\Column(type="string", length=255)
     */
    private string $address = '';

    /**
     * @ORM\Column(type="datetime")
     */
    private ?DateTimeInterface $update_time;

    /**
     * @ORM\Column(type="datetime")
     */
    private ?DateTimeInterface $created_time;

    /**
     * @ORM\Column(type="string", length=64)
     */
    private string $auth = '';

    /**
     * @ORM\Column(type="string", length=64)
     */
    private string $url = '';

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @param int|null $id
     */
    public function setId(?int $id): void
    {
        $this->id = $id;
    }

    /**
     * @return int|null
     */
    public function getUserId(): ?int
    {
        return $this->user_id;
    }

    /**
     * @param int|null $user_id
     */
    public function setUserId(?int $user_id): void
    {
        $this->user_id = $user_id;
    }

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * @param string $name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

    /**
     * @return string
     */
    public function getTemperatureRange(): string
    {
        return $this->temperature_range;
    }

    /**
     * @param string $temperature_range
     */
    public function setTemperatureRange(string $temperature_range): void
    {
        $this->temperature_range = $temperature_range;
    }

    /**
     * @return string
     */
    public function getHumidityRange(): string
    {
        return $this->humidity_range;
    }

    /**
     * @param string $humidity_range
     */
    public function setHumidityRange(string $humidity_range): void
    {
        $this->humidity_range = $humidity_range;
    }

    /**
     * @return string
     */
    public function getLightingSchedule(): string
    {
        return $this->lighting_schedule;
    }

    /**
     * @param string $lighting_schedule
     */
    public function setLightingSchedule(string $lighting_schedule): void
    {
        $this->lighting_schedule = $lighting_schedule;
    }

    /**
     * @return string
     */
    public function getAddress(): string
    {
        return $this->address;
    }

    /**
     * @param string $address
     */
    public function setAddress(string $address): void
    {
        $this->address = $address;
    }

    /**
     * @return DateTimeInterface|null
     */
    public function getUpdateTime(): ?DateTimeInterface
    {
        return $this->update_time;
    }

    /**
     * @param DateTimeInterface|null $update_time
     */
    public function setUpdateTime(?DateTimeInterface $update_time): void
    {
        $this->update_time = $update_time;
    }

    /**
     * @return DateTimeInterface|null
     */
    public function getCreatedTime(): ?DateTimeInterface
    {
        return $this->created_time;
    }

    /**
     * @param DateTimeInterface|null $created_time
     */
    public function setCreatedTime(?DateTimeInterface $created_time): void
    {
        $this->created_time = $created_time;
    }

    /**
     * @return string
     */
    public function getAuth(): string
    {
        return $this->auth;
    }

    /**
     * @param string $auth
     */
    public function setAuth(string $auth): void
    {
        $this->auth = $auth;
    }

    /**
     * @return string
     */
    public function getUrl(): string
    {
        return $this->url;
    }

    /**
     * @param string $url
     */
    public function setUrl(string $url): void
    {
        $this->url = $url;
    }

}

src/Entity/User.php
<?php

namespace App\Entity;

use DateTimeInterface;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields={"email"}, message="Paskyra su tokiu el. paštu jau yra sukurtaĄ")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private ?int $id = null;

    /**
     * @ORM\Column(type="string", length=70)
     */
    private string $name = '';

    /**
     * @ORM\Column(type="string", length=100)
     */
    private string $email = '';

    /**
     * @ORM\Column(type="string", length=255)
     */
    private string $password = '';

    /**
     * @ORM\Column(type="boolean")
     */
    private ?bool $admin = null;

    /**
     * @ORM\Column(type="datetime")
     */
    private ?DateTimeInterface $created_date = null;

    /**
     * @ORM\Column(type="datetime")
     */
    private ?DateTimeInterface $update_date = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getAdmin(): ?bool
    {
        return $this->admin;
    }

    public function setAdmin(bool $admin): self
    {
        $this->admin = $admin;

        return $this;
    }

    public function getCreatedDate(): ?DateTimeInterface
    {
        return $this->created_date;
    }

    public function setCreatedDate(DateTimeInterface $created_date): self
    {
        $this->created_date = $created_date;

        return $this;
    }

    public function getUpdateDate(): ?DateTimeInterface
    {
        return $this->update_date;
    }

    public function setUpdateDate(DateTimeInterface $update_date): self
    {
        $this->update_date = $update_date;

        return $this;
    }

    public function getRoles(): array
    {
        return array($this->admin == 1 ? "ROLE_ADMIN" : "ROLE_USER");
    }

    public function getSalt()
    {
        return null;
    }

    public function getUsername(): string
    {
        return $this->name;
    }

    public function eraseCredentials() {}

    public function __toString() {
        return $this->name;
    }
}

templates/table/customer-table.html.twig
<table class="table table-striped table-sm" id="users-table">
    <thead>
    <tr>
        <th>#</th>
        <th>Pavadinimas</th>
        <th>El. paštas</th>
        <th>Rolė</th>
        <th>Sukurtas</th>
        <th>Atnaujintas</th>
        <th class="text-center">Redaguoti</th>
        <th class="text-center">Pašalinti</th>
    </tr>
    </thead>
    <tbody>
    {% for user in users %}
        <tr>
            <td>{{ user.id }}</td>
            <td>{{ user.name }}</td>
            <td>{{ user.email }}</td>
            <td>{{ user.admin ? 'Prižiūrinti įmonė' : 'Klientas' }}</td>
            <td>{{ user.createdDate|date('Y-m-d H:i:s') }}</td>
            <td>{{ user.updateDate|date('Y-m-d H:i:s') }}</td>
            <td class="text-center">
                <a class="black" href="{{ path('edit_user', { 'id' : user.id }) }}">
                    <i class="fas fa-edit"></i>
                </a>
            </td>
            <td class="text-center">
                <a data-record-id="{{ user.id }}" data-record-title="{{ user.name }}"
                   data-url="vartotojai" data-name="users-table"
                   data-toggle="modal" data-target="#confirm-delete">
                    <i class="fas fa-trash"></i>
                </a>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>

templates/table/data-table.html.twig
<table class="table table-striped table-sm" id="terrariums-data-table">
    <thead>
    <tr>
        <th>Vartotojas</th>
        <th>Terariumas</th>
        <th>Temperatūra</th>
        <th>Drėgmė</th>
        <th>Apšvietimas</th>
        <th>Šildymas</th>
        <th>Laikas</th>
    </tr>
    </thead>
    <tbody>
    {% for terrariumData in terrariumsData %}
        <tr>
            <td>{{ terrariumData.userName }}</td>
            <td>{{ terrariumData.terName }}</td>
            <td>{{ terrariumData.temperature }}°C</td>
            <td>{{ terrariumData.humidity }}%</td>
            <td>{{ terrariumData.light }}</td>
            <td>{{ terrariumData.heater }}</td>
            <td>{{ terrariumData.time|date('Y-m-d H:i:s') }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

templates/table/message-table.html.twig
<table class="table table-striped table-sm" id="messages-table">
    <thead>
    <tr>
        <th>Terariumas</th>
        <th>Pranešimas</th>
        <th>Laikas</th>
    </tr>
    </thead>
    <tbody>
    {% for message in messages %}
        {% if message.active == 1 %}
            <tr style="color: red">
        {% else %}
            <tr>
        {% endif %}
        <td>{{ message.name }}</td>
        <td>{{ message.message }}</td>
        <td>{{ message.time }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

templates/table/route-table.html.twig
<table class="table table-striped table-sm">
    <thead>
    <tr>
        <th>Terariumas</th>
        <th>Adresas</th>
        <th class="text-center">Temperatūros ribos</th>
        <th>Temperatūra</th>
        <th class="text-center">Drėgmės ribos</th>
        <th>Drėgmė</th>
        <th>Reitingas</th>
        <th>Statusas</th>
    </tr>
    </thead>
    <tbody>
    {% for route in routes %}
        <tr style="color: {{ route.condition }}">
            <td>{{ route.terrarium }}</td>
            <td>{{ route.address }}</td>
            <td class="text-center">{{ route.temperature_limit }}</td>
            <td>{{ route.temperature }}</td>
            <td class="text-center">{{ route.humidity_limit }}</td>
            <td>{{ route.humidity }}</td>
            <td>{{ route.rating }}</td>
            <td>{{ route.status }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

templates/table/terrarium-table.html.twig
<table class="table table-striped table-sm" id="terrariums-table">
    <thead>
    <tr>
        <th>#</th>
        <th>Vartotojas</th>
        <th>Pavadinimas</th>
        <th>Temperatūra</th>
        <th>Drėgmė</th>
        <th>Apšvietimas</th>
        <th>Adresas</th>
        <th>Sukurtas</th>
        <th>Atnaujintas</th>
        {% if is_granted('ROLE_ADMIN') %}
            <th class="text-center">Veiksmai</th>
        {% endif %}
    </tr>
    </thead>
    <tbody>
    {% for terrarium in terrariums %}
        <tr>
            <td>{{ terrarium.id }}</td>
            <td>{{ userNames[terrarium.userId] }}</td>
            <td>{{ terrarium.name }}
                {% if is_granted('ROLE_ADMIN') %}
                    <i class="fas fa-tags" title="{{ terrarium.auth }}"></i>
                {% endif %}
            </td>
            <td>{{ terrarium.temperatureRange }}°C</td>
            <td>{{ terrarium.humidityRange }}%</td>
            <td>{{ terrarium.lightingSchedule }}</td>
            <td>{{ terrarium.address }}</td>
            <td>{{ terrarium.createdTime|date('Y-m-d H:i:s') }}</td>
            <td>{{ terrarium.updateTime|date('Y-m-d H:i:s') }}</td>
            {% if is_granted('ROLE_ADMIN') %}
                <td class="text-center">
                    <a data-record-url="{{ terrarium.url }}" data-record-title="{{ terrarium.name }}"
                       data-toggle="modal" data-target="#start-stream">
                        <i class="fas fa-camera"></i>
                    </a>
                    <a class="black" href="{{ path('edit_terrarium', { 'id' : terrarium.id }) }}">
                        <i class="fas fa-edit"></i>
                    </a>
                    <a data-record-id="{{ terrarium.id }}" data-record-title="{{ terrarium.name }}"
                       data-url="terariumai" data-name="terrariums-table"
                       data-toggle="modal" data-target="#confirm-delete">
                        <i class="fas fa-trash"></i>
                    </a>
                </td>
            {% endif %}
        </tr>
    {% endfor %}
    </tbody>
</table>